### ISSUE TITLE
Is this repo for conerf or hypernerf ?

### ISSUE THREAD

**Issue by yaoyuan13** [kacperkan/conerf#1]
I saw your updates in README are about hyperNerf but the title is conerf.

**Comment by kacperkan** [comment]
Hi @yaoyuan13 

We're still working towards releasing the final codebase (especially readme!). We've built CoNeRF using [HyperNeRF's codebase](https://github.com/google/hypernerf) hence the overlap of namespaces

**Comment by yaoyuan13** [comment]
Got it, thanks. Look forward to the final codebase.
